
package co.com.bancodeoccidente.servicios.negocio.administracion.wsdl.ejecucionprocesomultipropositos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import co.com.bancodeoccidente.servicios.negocio.administracion.xsd.ejecutarproceso.MnsjeEntradaType;
import co.com.bancodeoccidente.servicios.negocio.administracion.xsd.ejecutarproceso.MnsjeSalidaType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EjecucionProcesoMultiPropositosPortType", targetNamespace = "http://bancodeoccidente.com.co/Servicios/Negocio/Administracion/wsdl/EjecucionProcesoMultiPropositos")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    co.com.bancodeoccidente.servicios.negocio.administracion.xsd.ejecutarproceso.ObjectFactory.class,
    co.com.bancodeoccidente.servicios.base.encabezadossoa.ObjectFactory.class
})
public interface EjecucionProcesoMultiPropositosPortType {


    /**
     * 
     * @param input
     * @return
     *     returns co.com.bancodeoccidente.servicios.negocio.administracion.xsd.ejecutarproceso.MnsjeSalidaType
     */
    @WebMethod(action = "http://bancodeoccidente.com.co/Servicios/Negocio/Administracion/wsdl/EjecucionProcesoMultiPropositos/ejecutarProceso")
    @WebResult(name = "EjecutarProcesoRta", targetNamespace = "http://bancodeoccidente.com.co/Servicios/Negocio/Administracion/xsd/EjecutarProceso", partName = "output")
    public MnsjeSalidaType ejecutarProceso(
        @WebParam(name = "EjecutarProceso", targetNamespace = "http://bancodeoccidente.com.co/Servicios/Negocio/Administracion/xsd/EjecutarProceso", partName = "input")
        MnsjeEntradaType input);

}
